# Generated by Django 2.1.5 on 2019-01-23 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractTrackerStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker_status', models.PositiveIntegerField(choices=[(0, 'Off'), (1, 'On')], default=1, verbose_name='Tracker: Status')),
            ],
        ),
        migrations.CreateModel(
            name='GatekeeperTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker_name', models.CharField(help_text='What is this tracker for?', max_length=200, verbose_name='Tracker: Title')),
                ('tracker_date_created', models.DateTimeField(auto_now_add=True, verbose_name='Tracker: Date Created')),
                ('tracker_date_modified', models.DateTimeField(auto_now=True, verbose_name='Tracker: Last Updated')),
                ('tracker_location', models.CharField(choices=[('tracker-head-top', 'Head - near top'), ('tracker-head-bottom', 'Head - near bottom'), ('tracker-body-top', 'Body - near top'), ('tracker-body-bottom', 'Body - near bottom')], max_length=80, verbose_name='Tracker: Page Location')),
                ('tracker_code', models.TextField(help_text='Paste your tracking code block here.', verbose_name='Tracker: CODE')),
                ('tracker_live_as_of', models.DateTimeField(verbose_name='Tracker: Live "as of" Date')),
                ('tracker_publish_status', models.PositiveIntegerField(choices=[(-1, 'NEVER Available'), (0, 'USE "Live as of Date"'), (1, 'ALWAYS Available')], default=0, verbose_name='Tracker: Publish Status')),
                ('tracker_expires', models.DateTimeField(blank=True, help_text='Leave blank if never-ending.', null=True, verbose_name='Tracker: Expire Date')),
            ],
            options={
                'verbose_name': 'Gatekeeper Tracker',
                'verbose_name_plural': 'Gatekeeper Trackers',
            },
        ),
        migrations.CreateModel(
            name='SimpleTracker',
            fields=[
                ('abstracttrackerstatus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tracking.AbstractTrackerStatus')),
                ('tracker_name', models.CharField(help_text='What is this tracker for?', max_length=200, verbose_name='Tracker: Title')),
                ('tracker_date_created', models.DateTimeField(auto_now_add=True, verbose_name='Tracker: Date Created')),
                ('tracker_date_modified', models.DateTimeField(auto_now=True, verbose_name='Tracker: Last Updated')),
                ('tracker_location', models.CharField(choices=[('tracker-head-top', 'Head - near top'), ('tracker-head-bottom', 'Head - near bottom'), ('tracker-body-top', 'Body - near top'), ('tracker-body-bottom', 'Body - near bottom')], max_length=80, verbose_name='Tracker: Page Location')),
                ('tracker_code', models.TextField(help_text='Paste your tracking code block here.', verbose_name='Tracker: CODE')),
            ],
            options={
                'verbose_name': 'Simple Tracker',
                'verbose_name_plural': 'Simple Trackers',
            },
            bases=('tracking.abstracttrackerstatus', models.Model),
        ),
    ]
