# Generated by Django 2.1.5 on 2019-01-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatekeepertracker',
            name='tracker_live_as_of',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tracker: Live "as of" Date'),
        ),
    ]
